### PR TITLE
Misc Backend Fixes

### LINKED ISSUE #40: Misc backend fixes

### PR DESCRIPTION
**Pull request by ctc-devops**
Authors:
 ### What does this PR contain?
 ### How did you test these changes?
 ### Attach images (if applicable)
 Closes #40

### CODE REVIEW

File: routes/donations.js [hunk 1]
```diff
@@ -278,8 +280,38 @@ donationsRouter.put('/:donationId', async (req, res) => {
...
+      RETURNING *;`,
+      { donationId, furniture },
+    );
+
+    donation[0].pictures = picturesRes;
+    donation[0].furniture = furnitureRes;
+
     res.status(200).send(keysToCamel(donation));
   } catch (err) {
+    console.log(err.message);
```
Comment (ctc-devops) [inline routes/donations.js:401]: ⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

File: routes/donations.js [hunk 2]
```diff
@@ -278,8 +280,91 @@ donationsRouter.put('/:donationId', async (req, res) => {
...
+    const pictureIds = await db.query(`SELECT id FROM pictures WHERE donation_id=$(donationId)`, {
+      donationId,
+    });
+    const {
+      putArr: picturePut,
+      postArr: picturePost,
+      delArr: pictureDel,
+    } = diffArray(pictureIds, furniture);
+
+    console.log('PUT:', picturePut);
```
Comment (ctc-devops) [inline routes/donations.js]: ⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

File: routes/donations.js [hunk 3]
```diff
@@ -278,8 +280,91 @@ donationsRouter.put('/:donationId', async (req, res) => {
...
+    console.log('POST:', picturePost);
```
Comment (ctc-devops) [inline routes/donations.js]: ⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

File: routes/donations.js [hunk 4]
```diff
@@ -278,8 +280,91 @@ donationsRouter.put('/:donationId', async (req, res) => {
...
+    console.log('DELETE:', pictureDel);
```
Comment (ctc-devops) [inline routes/donations.js]: ⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

File: routes/donations.js [hunk 5]
```diff
@@ -278,8 +280,91 @@ donationsRouter.put('/:donationId', async (req, res) => {
...
+        WHERE id in (
+            SELECT id
+            FROM
+                json_to_recordset($(furnitureDel:json))
+            AS data(id integer)
+        )
+        RETURNING *`,
+      { donationId, furnitureDel },
+    );
+    console.log(furnitureDeleteRes);
```
Comment (ctc-devops) [inline routes/donations.js]: ⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

**Review by jrock-3 — APPROVED** [review]
